name: Docs Deploy

on:
    push:
        branches:
            - '0.12'
    workflow_dispatch:

permissions:
    contents: write

jobs:
    docs-deploy:
        name: "Build & Deploy"
        runs-on: ubuntu-latest
        steps:
            - name: Output infos
              run: |
                  echo "${{ github.event.pull_request.merge_commit_sha }}"
                  echo "${{ github.event.pull_request.head.sha }}"

            - name: Checkout project
              uses: actions/checkout@v7
              with:
                  ref: "${{ github.event.pull_request.head.sha }}"

            - name: Git infos
              run: |
                  git rev-parse HEAD
                  git branch --show-current

            - uses: actions/setup-python@v7
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                  pip install -r docs/requirements.txt

            - name: List dependencies
              run: |
                  pip list

            - name: Sphinx build
              run: |
                  sphinx-build docs docs/_build

            - name: Deploy
              uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
              with:
                  publish_branch: gh-pages
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs/_build/
                  force_orphan: true
